// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelecomSystem.Infrastructure;

#nullable disable

namespace TelecomSystem.Infrastructure.Migrations
{
    [DbContext(typeof(TelecomDbContext))]
    partial class TelecomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelecomSystem.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OperadoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanoContratado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Status")
                        .HasColumnType("character(1)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperadoraId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("TelecomSystem.Domain.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("TelecomSystem.Domain.Entities.Operadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContatoSuporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoServico")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Operadoras");
                });

            modelBuilder.Entity("TelecomSystem.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("TelecomSystem.Domain.Entities.Operadora", "Operadora")
                        .WithMany()
                        .HasForeignKey("OperadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operadora");
                });

            modelBuilder.Entity("TelecomSystem.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("TelecomSystem.Domain.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });
#pragma warning restore 612, 618
        }
    }
}
